# The joint state controller handles publishing transforms for any moving joints
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
rear_left_wheel_spinning_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_left_wheel_spinning_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

rear_right_wheel_spinning_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_right_wheel_spinning_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

front_left_wheel_steering_joint_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_wheel_steering_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

front_right_wheel_steering_joint_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_wheel_steering_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}